<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_73) on Mon Aug 05 11:30:48 IST 2019 -->
<title>${group}</title>
<meta name="date" content="2019-08-05">
<link rel="stylesheet" type="text/css" href="${relativeDir}stylesheet.css" title="Style">
<script type="text/javascript" src="${relativeDir}script.js"></script>
<script type="text/javascript" src="${relativeDir}js/jquery-3.4.1.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="${group}";
        }
    }
    catch(err) {
    }
    
    function toggleVisibility(checkbox) {
    	var th = $(checkbox).parent('th');
    	var table = $(checkbox).closest('table');
    	var index = th.index();

		if ($(checkbox).is(":checked")) {  	
	    	$.each(table.find('tr td:nth-child(' + (index + 1) + ')'), function(){ 
	            if ($(this).find('img').length != 0) {
	            	$(this).closest('tr').hide();
	            }
	        });
        } else {
        	$.each(table.find('tr'), function(){ 
	            $(this).closest('tr').show();
	        });
        }
    }
//-->
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="${relativeDir}overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="${relativeDir}help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="${relativeDir}index.html?${packageDir}/${group}.html" target="_top">Frames</a></li>
<li><a href="${group}.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="${relativeDir}allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">${packageName}</div>
<h2 title="Class ${group}" class="title">Class ${group}</h2>
</div>
<div class="contentContainer">
<ul class="inheritance">
</ul>
</li>
</ul>
</li>
</ul>
<div class="description">
<ul class="blockList">
<li class="blockList">
<hr>
<br>
<!--pre>public class <span class="typeNameLabel">${group}</span>
extends org.eclipse.swt.widgets.Layout</pre>
<div class="block">A layout manager that lays out child controls in absolute positions.  
 Each control's bounds is specified by setting an SWT Rectangle
 object specifying the control's bounds into the control's layout data.
 <p>
 Use this layout manager whenever you would have used a null layout
 previously.</div-->
<!--dl>
<dt><span class="simpleTagLabel">Since:</span></dt>
<dd>3.3</dd>
</dl-->
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
<!-- ======== CONSTRUCTOR SUMMARY ======== -->
<ul class="blockList">
<li class="blockList"><a name="constructor.summary">
<!--   -->
</a>
<h3>Widget Attribute Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Constructor Summary table, listing constructors, and an explanation" style="width: min-content">
<caption><span>Attributes</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colOne" scope="col"></th>
<#list widgets as widget>
<th class="colOne" scope="col" colspan="4">${widget.nativeClassName}</th>
</#list>

</tr>

<tr>
<th class="colOne" scope="col">Attribute</th>
<#list widgets as widget>
<th class="colOne" scope="col"><input type="checkbox" onClick="toggleVisibility(this)"> <br>Test</th>
<th class="colOne" scope="col"><input type="checkbox" onClick="toggleVisibility(this)"> <br>Get</th>
<th class="colOne" scope="col"><input type="checkbox" onClick="toggleVisibility(this)"> <br>Set</th>
<th class="colLast" scope="col"><input type="checkbox" onClick="toggleVisibility(this)"> <br>Desc</th>
</#list>

</tr>

<tr>
<th class="colOne" scope="col">Widget Override</th>
<#list widgets as widget>
<th class="colOne" scope="col" colspan="4" style="text-align: center">${widget.name}</th>
</#list>
</tr>

<tr>
<th class="colOne" scope="col">Score</th>
<#list widgets as widget>
<th class="colOne" scope="col" colspan="4" style="text-align: center">${widget.similarity}</th>
</#list>
</tr>

<#list attributesMap as item>
<#assign key = item.getKey()/>
<#assign attributes = item.getValue()/>


<tr class="altColor">
<th class="colOne" scope="col" colspan="${(widgets?size * 4) + 1}"><a target="_blank" href="${key}">${key}</a></th>

</tr>


<#list attributes as attribute>
<#if attribute.attributeName != 'attributeUnderTest'> 
<tr class="altColor">

<td class="colOne" ><code><span class="memberNameLink"><a target="_blank" href="<#if attribute.generatorUrl == 'help-doc.html'>${relativeDir}</#if>${attribute.generatorUrl!"#"}">${attribute.namespace}${attribute.attributeName}</a></span></code>&nbsp;</td>

<#assign x = 0>
<#list widgets as widget>
<#assign key = widget.name + "" + widget.nativeClassName + "" + attribute.attributeName>
<#assign notSupported = attributeMap[key]?? && attributeMap[key].xmlTest?? && attributeMap[key].xmlTest =='notsupported'>
<td class="colOne" style="background: ${colors[x]}; border-right: solid 1px #fff;"><code><span class="memberNameLink"><#if attributeMap[key]?? && attributeMap[key].xmlTest?? && !notSupported><img width="20px" src="${relativeDir}img/${attributeMap[key].xmlTest}.png"/></#if></span></code>&nbsp;</td>
<td class="colOne" style="background: ${colors[x]}; border-right: solid 1px #fff;"><code><span class="memberNameLink"><#if attributeMap[key]?? && attributeMap[key].getterMethod?? && !notSupported><img width="20px" height="20px" src="${relativeDir}img/pass.png"/></#if></span></code>&nbsp;</td>
<td class="colOne" style="background: ${colors[x]}; border-right: solid 1px #fff;"><code><span class="memberNameLink"><#if attributeMap[key]??  && attributeMap[key].constructor?? && !notSupported><img width="20px" height="20px" src="${relativeDir}img/pass-con.png"/><#elseif attributeMap[key]??  && attributeMap[key].setterMethod?? && !notSupported><img width="20px" height="20px" src="${relativeDir}img/pass.png"/></#if></span></code>&nbsp;</td>
<td class="colOne" style="background: ${colors[x]}; border-right: solid 1px #fff;"><code><span class="memberNameLink"><#if attributeMap[key]??  && attributeMap[key].description?? && attributeMap[key].description != '' && !notSupported><img title='${attributeMap[key].description}'   alt='${attributeMap[key].description}' width="20px" src="${relativeDir}img/info-icon.png"/></#if></span></code>&nbsp;</td>
<#assign x = x + 1>
</#list>

</tr>
</#if>
</#list>
</#list>
</table>

<h3>Ignored Attribute Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Constructor Summary table, listing constructors, and an explanation" style="width: min-content">
<caption><span>Attributes</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colOne" scope="col"></th>
<#list widgets as widget>
<th class="colOne" scope="col" colspan="4">${widget.nativeClassName} <#list widget.ignoredAttributes as ignoredAttribute>${ignoredAttribute}<br></#list></th>
</#list>

</tr>
</table>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="${relativeDir}overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="${relativeDir}help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="${relativeDir}index.html?${packageDir}/${group}.html" target="_top">Frames</a></li>
<li><a href="${group}.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="${relativeDir}allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</body>
</html>
