//start - license
/*
 * Copyright (c) 2025 Ashera Cordova
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
//end - license
/* SimpleExpressionParser.java */
/* Generated By:JavaCC: Do not edit this line. SimpleExpressionParser.java */
package expr;

import java.util.*;

public class SimpleExpressionParser implements SimpleExpressionParserConstants {
        private Map<String, Double> variables = new HashMap<>();

    public Map<String, Double> getVariables() {
                return variables;
        }

        public void setVariables(Map<String, Double> variables) {
                this.variables = variables;
        }
    public static void main(String[] args) throws Exception {
        SimpleExpressionParser parser = new SimpleExpressionParser(new java.io.StringReader(""));
        java.io.BufferedReader br = new java.io.BufferedReader(new java.io.InputStreamReader(System.in));
        System.out.println("Expression parser REPL. Type 'quit' to exit.");
        Map<String, Double> vars = new HashMap<>();
        vars.put("pi", Math.PI);
        vars.put("e", Math.E);

                parser.ReInit(new java.io.StringReader("x = 3;\n"
                                + "y = 0;\n"
                                + "while (x > 0) { y = y + x; x = x - 1; };\n"
                                + "y"));
        parser.setVariables(vars);
        Expr expr = parser.StatementList();
        System.out.println(expr.eval(vars));





    }

  static final public Expr StatementList() throws ParseException {Expr e = null; StatementListExpr expr = new StatementListExpr();;
    label_1:
    while (true) {
      e = Statement();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SEMICOLON:{
        jj_consume_token(SEMICOLON);
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        ;
      }
expr.add(e);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case LPAREN:
      case NOT:
      case IF:
      case NUMBER:
      case WHILE:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

  static final public Expr Statement() throws ParseException {Expr e; Expr cond; Expr body;
    if (jj_2_1(2)) {
      e = AssignmentExpression();
{if ("" != null) return e;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case LPAREN:
      case NOT:
      case IF:
      case NUMBER:
      case IDENTIFIER:{
        e = IfExpression();
{if ("" != null) return e;}
        break;
        }
      case WHILE:{
        jj_consume_token(WHILE);
        jj_consume_token(LPAREN);
        cond = ConditionalExpression();
        jj_consume_token(RPAREN);
        jj_consume_token(LF_BRACKET);
        body = StatementList();
        jj_consume_token(RF_BRACKET);
{if ("" != null) return new WhileExpr(cond, body);}
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Expr IfExpression() throws ParseException {Expr cond, thenExpr, elseExpr; Expr normal;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IF:{
      jj_consume_token(IF);
      jj_consume_token(LPAREN);
      cond = ConditionalExpression();
      jj_consume_token(RPAREN);
      thenExpr = ConditionalExpression();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ELSE:{
        jj_consume_token(ELSE);
        elseExpr = ConditionalExpression();
{if ("" != null) return new Ternary(cond, thenExpr, elseExpr);}
        break;
        }
      default:
        jj_la1[3] = jj_gen;
{if ("" != null) return new Ternary(cond, thenExpr, new NumberLiteral(0.0));}
      }
      break;
      }
    case PLUS:
    case MINUS:
    case LPAREN:
    case NOT:
    case NUMBER:
    case IDENTIFIER:{
      normal = ConditionalExpression();
{if ("" != null) return normal;}
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Expr ConditionalExpression() throws ParseException {Expr e1, e2, e3;
    e1 = LogicalOrExpression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case QUESTION:{
      jj_consume_token(QUESTION);
      e2 = ConditionalExpression();
      jj_consume_token(COLON);
      e3 = ConditionalExpression();
{if ("" != null) return new Ternary(e1, e2, e3);}
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public Expr LogicalOrExpression() throws ParseException {Expr left, right;
    left = LogicalAndExpression();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_2;
      }
      jj_consume_token(OR);
      right = LogicalAndExpression();
left = new BinaryOp("||", left, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr LogicalAndExpression() throws ParseException {Expr left, right;
    left = EqualityExpression();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      jj_consume_token(AND);
      right = EqualityExpression();
left = new BinaryOp("&&", left, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr EqualityExpression() throws ParseException {Expr left, right; Token t;
    left = RelationalExpression();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:
      case NEQ:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:{
        t = jj_consume_token(EQ);
        break;
        }
      case NEQ:{
        t = jj_consume_token(NEQ);
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = RelationalExpression();
left = new BinaryOp(t.image, left, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr RelationalExpression() throws ParseException {Expr left, right; Token t;
    left = AdditiveExpression();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LTE:
      case GTE:
      case LT:
      case GT:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        t = jj_consume_token(LT);
        break;
        }
      case GT:{
        t = jj_consume_token(GT);
        break;
        }
      case LTE:{
        t = jj_consume_token(LTE);
        break;
        }
      case GTE:{
        t = jj_consume_token(GTE);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = AdditiveExpression();
left = new BinaryOp(t.image, left, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr AdditiveExpression() throws ParseException {Expr left, right; Token t;
    left = MultiplicativeExpression();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        t = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        t = jj_consume_token(MINUS);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = MultiplicativeExpression();
left = new BinaryOp(t.image, left, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr MultiplicativeExpression() throws ParseException {Expr left, right; Token t;
    left = UnaryExpression();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:
      case DIV:
      case MOD:
      case POW:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        t = jj_consume_token(MULT);
        break;
        }
      case DIV:{
        t = jj_consume_token(DIV);
        break;
        }
      case MOD:{
        t = jj_consume_token(MOD);
        break;
        }
      case POW:{
        t = jj_consume_token(POW);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = UnaryExpression();
left = new BinaryOp(t.image, left, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Expr UnaryExpression() throws ParseException {Token t; Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:
    case NOT:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        t = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        t = jj_consume_token(MINUS);
        break;
        }
      case NOT:{
        t = jj_consume_token(NOT);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      e = UnaryExpression();
{if ("" != null) return new UnaryOp(t.image, e);}
      break;
      }
    case LPAREN:
    case NUMBER:
    case IDENTIFIER:{
      e = Primary();
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Expr Primary() throws ParseException {Token num, id; Expr e; List<Expr> args;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMBER:{
      num = jj_consume_token(NUMBER);
{if ("" != null) return new NumberLiteral(Double.parseDouble(num.image));}
      break;
      }
    case IDENTIFIER:{
      id = jj_consume_token(IDENTIFIER);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        jj_consume_token(LPAREN);
        args = ArgumentList();
        jj_consume_token(RPAREN);
{if ("" != null) return new FunctionCall(id.image, args);}
        break;
        }
      default:
        jj_la1[18] = jj_gen;
{if ("" != null) return new Variable(id.image);}
      }
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      e = ConditionalExpression();
      jj_consume_token(RPAREN);
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public List<Expr> ArgumentList() throws ParseException {List<Expr> list = new ArrayList<>(); Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:
    case LPAREN:
    case NOT:
    case NUMBER:
    case IDENTIFIER:{
      e = ConditionalExpression();
list.add(e);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          break label_8;
        }
        jj_consume_token(COMMA);
        e = ConditionalExpression();
list.add(e);
      }
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
{if ("" != null) return list;}
    throw new Error("Missing return statement in function");
}

  static final public Expr Expression() throws ParseException {Expr e;
    e = AssignmentExpression();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Expr AssignmentExpression() throws ParseException {Token id; Expr rhs; Expr e;
    if (jj_2_2(2)) {
      id = jj_consume_token(IDENTIFIER);
      jj_consume_token(ASSIGN);
      rhs = Expression();
{if ("" != null) return new Assignment(id.image, rhs);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case LPAREN:
      case NOT:
      case NUMBER:
      case IDENTIFIER:{
        e = RelationalExpression();
{if ("" != null) return e;}
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_3R_LogicalAndExpression_224_5_28()
 {
    if (jj_3R_EqualityExpression_231_5_29()) return true;
    return false;
  }

  static private boolean jj_3R_Primary_268_7_25()
 {
    return false;
  }

  static private boolean jj_3R_Primary_270_5_23()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_ConditionalExpression_208_5_26()) return true;
    return false;
  }

  static private boolean jj_3R_Primary_267_7_24()
 {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_Primary_266_5_22()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Primary_267_7_24()) {
    jj_scanpos = xsp;
    if (jj_3R_Primary_268_7_25()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Primary_265_5_20()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Primary_265_5_21()) {
    jj_scanpos = xsp;
    if (jj_3R_Primary_266_5_22()) {
    jj_scanpos = xsp;
    if (jj_3R_Primary_270_5_23()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_Primary_265_5_21()
 {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  static private boolean jj_3R_LogicalOrExpression_217_5_27()
 {
    if (jj_3R_LogicalAndExpression_224_5_28()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpression_260_5_19()
 {
    if (jj_3R_Primary_265_5_20()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpression_259_5_16()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_UnaryExpression_259_5_18()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpression_260_5_19()) return true;
    }
    return false;
  }

  static private boolean jj_3R_UnaryExpression_259_5_18()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(1)) {
    jj_scanpos = xsp;
    if (jj_scan_token(2)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) return true;
    }
    }
    if (jj_3R_UnaryExpression_259_5_16()) return true;
    return false;
  }

  static private boolean jj_3R_ConditionalExpression_208_5_26()
 {
    if (jj_3R_LogicalOrExpression_217_5_27()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_253_7_17()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(3)) {
    jj_scanpos = xsp;
    if (jj_scan_token(4)) {
    jj_scanpos = xsp;
    if (jj_scan_token(5)) {
    jj_scanpos = xsp;
    if (jj_scan_token(6)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_252_5_14()
 {
    if (jj_3R_UnaryExpression_259_5_16()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultiplicativeExpression_253_7_17()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_AssignmentExpression_291_11_10()
 {
    if (jj_3R_RelationalExpression_238_5_11()) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_246_7_15()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(1)) {
    jj_scanpos = xsp;
    if (jj_scan_token(2)) return true;
    }
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_245_5_12()
 {
    if (jj_3R_MultiplicativeExpression_252_5_14()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AdditiveExpression_246_7_15()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_AssignmentExpression_288_9_9()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3R_AssignmentExpression_291_11_10()) return true;
    }
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpression_239_7_13()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_AssignmentExpression_288_9_9()) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpression_238_5_11()
 {
    if (jj_3R_AdditiveExpression_245_5_12()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_RelationalExpression_239_7_13()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_EqualityExpression_231_5_29()
 {
    if (jj_3R_RelationalExpression_238_5_11()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
 /** Generated Token Manager. */
  static public SimpleExpressionParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
 /** Current token. */
  static public Token token;
 /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[23];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x2000000,0x25300086,0x25300086,0x400000,0x21300086,0x200,0x80000,0x40000,0x3000,0x3000,0x3c000,0x3c000,0x6,0x6,0x78,0x78,0x100006,0x21100086,0x80,0x21000080,0x800,0x21100086,0x21100086,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[2];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

 /** Constructor with InputStream. */
  public SimpleExpressionParser(java.io.InputStream stream) {
	  this(stream, null);
  }
 /** Constructor with InputStream and supplied encoding */
  public SimpleExpressionParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new SimpleExpressionParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

 /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
 /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

 /** Constructor. */
  public SimpleExpressionParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new SimpleExpressionParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

 /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new SimpleExpressionParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

 /** Constructor with generated Token Manager. */
  public SimpleExpressionParser(SimpleExpressionParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

 /** Reinitialise. */
  public void ReInit(SimpleExpressionParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

 /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[36];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 23; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 36; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

 /** Enable tracing. */
  static final public void enable_tracing() {
  }

 /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 2; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}

interface Expr {
    double eval(Map<String, Double> vars);
}

class NumberLiteral implements Expr {
    double value;
    NumberLiteral(double v){ value = v; }
    public double eval(Map<String, Double> vars){ return value; }
}

class Variable implements Expr {
    String name;
    Variable(String n){ name = n; }
    public double eval(Map<String, Double> vars) {
        Double v = vars.get(name);
        if (v == null) throw new RuntimeException("Undefined variable: " + name);
        return v;
    }
}

class UnaryOp implements Expr {
    String op; Expr expr;
    UnaryOp(String op, Expr e){ this.op = op; this.expr = e; }
    public double eval(Map<String, Double> vars) {
        double v = expr.eval(vars);
        switch(op) {
            case "+": return +v;
            case "-": return -v;
            case "!": return (v == 0.0) ? 1.0 : 0.0;
        }
        throw new RuntimeException("Unknown unary op: " + op);
    }
}

class BinaryOp implements Expr {
    String op; Expr left, right;
    BinaryOp(String op, Expr l, Expr r){ this.op = op; left = l; right = r; }
    public double eval(Map<String, Double> vars) {
        double a = left.eval(vars);
        double b = right.eval(vars);
        switch(op) {
            case "+": return a + b;
            case "-": return a - b;
            case "*": return a * b;
            case "/": return a / b;
            case "%": return a % b;
            case "^": return Math.pow(a,b);
            case "<": return (a < b) ? 1.0 : 0.0;
            case ">": return (a > b) ? 1.0 : 0.0;
            case "<=": return (a <= b) ? 1.0 : 0.0;
            case ">=": return (a >= b) ? 1.0 : 0.0;
            case "==": return (a == b) ? 1.0 : 0.0;
            case "!=": return (a != b) ? 1.0 : 0.0;
            case "&&": return ((a != 0.0) && (b != 0.0)) ? 1.0 : 0.0;
            case "||": return ((a != 0.0) || (b != 0.0)) ? 1.0 : 0.0;
        }
        throw new RuntimeException("Unknown binary op: " + op);
    }
}

class Ternary implements Expr {
    Expr cond, thenExpr, elseExpr;
    Ternary(Expr c, Expr t, Expr e){ cond = c; thenExpr = t; elseExpr = e; }
    public double eval(Map<String, Double> vars) {
        double c = cond.eval(vars);
        if (c != 0.0) return thenExpr.eval(vars);
        else return elseExpr.eval(vars);
    }
}

class FunctionCall implements Expr {
    String name; List<Expr> args;
    FunctionCall(String name, List<Expr> args){ this.name = name; this.args = args; }
    public double eval(Map<String, Double> vars)  {
        List<Double> evaluated = new ArrayList<>();
        for (Expr e : args) evaluated.add(e.eval(vars));
        if ("sin".equalsIgnoreCase(name)) return Math.sin(evaluated.get(0));
        if ("cos".equalsIgnoreCase(name)) return Math.cos(evaluated.get(0));
        if ("tan".equalsIgnoreCase(name)) return Math.tan(evaluated.get(0));
        if ("sqrt".equalsIgnoreCase(name)) return Math.sqrt(evaluated.get(0));
        if ("abs".equalsIgnoreCase(name)) return Math.abs(evaluated.get(0));
        if ("max".equalsIgnoreCase(name)) return Math.max(evaluated.get(0), evaluated.get(1));
        if ("min".equalsIgnoreCase(name)) return Math.min(evaluated.get(0), evaluated.get(1));
        if ("pow".equalsIgnoreCase(name)) return Math.pow(evaluated.get(0), evaluated.get(1));
        throw new RuntimeException("Unknown function: " + name);
    }
}


class WhileExpr implements Expr {
    private Expr cond;
    private Expr body;

    WhileExpr(Expr cond, Expr body) {
        this.cond = cond;
        this.body = body;
    }

    @Override
    public double eval(Map<String, Double> vars){
        double result = 0.0;
        while (cond.eval(vars) != 0.0) {
            result = body.eval(vars);
        }
        return result;
    }
}

class Assignment implements Expr {
    String name;
    Expr value;
    Assignment(String n, Expr v) { name = n; value = v; }

    public double eval(Map<String, Double> vars)  {
        double val = value.eval(vars);
        vars.put(name, val);
        return val;
    }
}

class StatementListExpr implements Expr {
    private List<Expr> exprs = new ArrayList<>();

    StatementListExpr() {
    }

        public void add(Expr expr) {
                exprs.add(expr);
        }

    @Override
    public double eval(Map<String, Double> vars){
        double result = 0.0;
        for (Expr expr : exprs) {
            result = expr.eval(vars);
        }
        return result;
    }
}
