//start - license
/*
 * Copyright (c) 2025 Ashera Cordova
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
//end - license
/* Generated By:JavaCC: Do not edit this line. SimpleExpressionParserConstants.java */
package expr;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleExpressionParserConstants {

 /** End of File. */
  int EOF = 0;
 /** RegularExpression Id. */
  int PLUS = 1;
 /** RegularExpression Id. */
  int MINUS = 2;
 /** RegularExpression Id. */
  int MULT = 3;
 /** RegularExpression Id. */
  int DIV = 4;
 /** RegularExpression Id. */
  int MOD = 5;
 /** RegularExpression Id. */
  int POW = 6;
 /** RegularExpression Id. */
  int LPAREN = 7;
 /** RegularExpression Id. */
  int RPAREN = 8;
 /** RegularExpression Id. */
  int QUESTION = 9;
 /** RegularExpression Id. */
  int COLON = 10;
 /** RegularExpression Id. */
  int COMMA = 11;
 /** RegularExpression Id. */
  int EQ = 12;
 /** RegularExpression Id. */
  int NEQ = 13;
 /** RegularExpression Id. */
  int LTE = 14;
 /** RegularExpression Id. */
  int GTE = 15;
 /** RegularExpression Id. */
  int LT = 16;
 /** RegularExpression Id. */
  int GT = 17;
 /** RegularExpression Id. */
  int AND = 18;
 /** RegularExpression Id. */
  int OR = 19;
 /** RegularExpression Id. */
  int NOT = 20;
 /** RegularExpression Id. */
  int IF = 21;
 /** RegularExpression Id. */
  int ELSE = 22;
 /** RegularExpression Id. */
  int ASSIGN = 23;
 /** RegularExpression Id. */
  int NUMBER = 24;
 /** RegularExpression Id. */
  int SEMICOLON = 25;
 /** RegularExpression Id. */
  int WHILE = 26;
 /** RegularExpression Id. */
  int LF_BRACKET = 27;
 /** RegularExpression Id. */
  int RF_BRACKET = 28;
 /** RegularExpression Id. */
  int IDENTIFIER = 29;
 /** RegularExpression Id. */
  int LETTER = 30;
 /** RegularExpression Id. */
  int DIGIT = 31;

 /** Lexical state. */
  int DEFAULT = 0;

 /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\"?\"",
    "\":\"",
    "\",\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"if\"",
    "\"else\"",
    "\"=\"",
    "<NUMBER>",
    "\";\"",
    "\"while\"",
    "\"{\"",
    "\"}\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
  };

}
