//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.21 at 02:50:44 PM IST 
//


package com.ashera.codegen.pojo.attrs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ashera.codegen.pojo.attrs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResourcesAttrFlag_QNAME = new QName("", "flag");
    private final static QName _ResourcesAttrEnum_QNAME = new QName("", "enum");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ashera.codegen.pojo.attrs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link Resources.DeclareStyleable }
     * 
     */
    public Resources.DeclareStyleable createResourcesDeclareStyleable() {
        return new Resources.DeclareStyleable();
    }

    /**
     * Create an instance of {@link Resources.Attr }
     * 
     */
    public Resources.Attr createResourcesAttr() {
        return new Resources.Attr();
    }

    /**
     * Create an instance of {@link Resources.DeclareStyleable.Attr }
     * 
     */
    public Resources.DeclareStyleable.Attr createResourcesDeclareStyleableAttr() {
        return new Resources.DeclareStyleable.Attr();
    }

    /**
     * Create an instance of {@link Resources.Attr.Enum }
     * 
     */
    public Resources.Attr.Enum createResourcesAttrEnum() {
        return new Resources.Attr.Enum();
    }

    /**
     * Create an instance of {@link Resources.Attr.Flag }
     * 
     */
    public Resources.Attr.Flag createResourcesAttrFlag() {
        return new Resources.Attr.Flag();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resources.Attr.Flag }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "flag", scope = Resources.Attr.class)
    public JAXBElement<Resources.Attr.Flag> createResourcesAttrFlag(Resources.Attr.Flag value) {
        return new JAXBElement<Resources.Attr.Flag>(_ResourcesAttrFlag_QNAME, Resources.Attr.Flag.class, Resources.Attr.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resources.Attr.Enum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enum", scope = Resources.Attr.class)
    public JAXBElement<Resources.Attr.Enum> createResourcesAttrEnum(Resources.Attr.Enum value) {
        return new JAXBElement<Resources.Attr.Enum>(_ResourcesAttrEnum_QNAME, Resources.Attr.Enum.class, Resources.Attr.class, value);
    }

}
